name: multimodalcourse
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.7=hf598326_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - numpy=2.2.6=py310h4d83441_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=hcd7f573_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h1d1bf99_2
  - scikit-learn=1.7.2=py310h660f142_0
  - setuptools=80.9.0=pyhff2d567_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.42.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.1
      - dill==0.4.0
      - exceptiongroup==1.3.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gensim==4.4.0
      - googletrans==4.0.2
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hyperframe==6.1.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - medclip==0.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - nltk==3.9.2
      - open-clip-torch==3.2.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scipy==1.15.3
      - six==1.17.0
      - smart-open==7.5.0
      - sympy==1.14.0
      - textaugment==2.0.0
      - textblob==0.19.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - wget==3.2
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /Users/zhaoyangwang/miniforge3/envs/multimodalcourse
